/* Diffie-Hellman Key Exchange */
#include <iostream>
#include <bits/stdc++.h>
#include <gmp.h>
using namespace std;


int main(){
	int g,p;
	cout<<" Enter the value of G and P ";
	cin>>g>>p;
	int a,b;
	cout<<"Enter the secret Key for Alice: ";
	cin>>a;
	cout<<"Enter the secreet key for Bob: ";
	cin>>b;
	int x,y;
	mpz_t temp;
	mpz_inits(temp,NULL);
	mpz_ui_pow_ui(temp,g,a);
	mpz_mod_ui(temp,temp,p);
	x=mpz_get_ui(temp);
	cout<<"key generated by Alice: "<<x<<endl;
	mpz_inits(temp,NULL);
	mpz_ui_pow_ui(temp,g,b);
	mpz_mod_ui(temp,temp,p);
	y=mpz_get_ui(temp);
	cout<<"Key generated by Bob: "<<y<<endl;

	int ka,kb;
	mpz_inits(temp,NULL);
	mpz_ui_pow_ui(temp,y,a);
	mpz_mod_ui(temp,temp,p);
	ka=mpz_get_ui(temp);

	mpz_inits(temp,NULL);
	mpz_ui_pow_ui(temp,x,b);
	mpz_mod_ui(temp,temp,p);
	kb=mpz_get_ui(temp);

	cout<<"Secret key of Alice : "<<ka<<endl;
	cout<<"Secret key of bob : "<<kb<<endl;

	return 0;

}

/* ******************************************************** Test Cases ***************************************************************************88

c157238@uselab121:~/Documents/c157238/Diffie-Hellman$ ./a.out
 Enter the value of G and P 9
23
Enter the secret Key for Alice: 4
Enter the secreet key for Bob: 3
key generated by Alice: 6
Key generated by Bob: 16
Secret key of Alice : 9
Secret key of bob : 9

------------------------------------------------------------------------------------------------------------------

c157238@uselab121:~/Documents/c157238/Diffie-Hellman$ ./a.out
 Enter the value of G and P 23
9
Enter the secret Key for Alice: 4
Enter the secreet key for Bob: 3
key generated by Alice: 4
Key generated by Bob: 8
Secret key of Alice : 1
Secret key of bob : 1

----------------------------------------------------------------------------------------------------------------------

c157238@uselab121:~/Documents/c157238/Diffie-Hellman$ ./a.out
 Enter the value of G and P 25
9
Enter the secret Key for Alice: 7
Enter the secreet key for Bob: 11
key generated by Alice: 7
Key generated by Bob: 4
Secret key of Alice : 4
Secret key of bob : 4
-------------------------------------------------------------------------------------------------------------------

c157238@uselab121:~/Documents/c157238/Diffie-Hellman$ ./a.out
 Enter the value of G and P 256
968
Enter the secret Key for Alice: 14589
Enter the secreet key for Bob: 9897654
key generated by Alice: 488
Key generated by Bob: 400
Secret key of Alice : 872
Secret key of bob : 872



